# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Slap Dash
tagline:          The Post Up
url:              http://rakunkel.github.io
paginate:         1
baseurl:          /
author:
  name:           rakunkel
  url:            https://twitter.com/rakunkel
  email:          rakunkel@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'